### ISSUE TITLE
Error when sending using private key

### ISSUE THREAD

**Issue by ATouhou** [kvhnuke/etherwallet#1521] opened 2018-01-14 00:39 UTC
(error_07) Please enter a valid password. TypeError: Cannot read property 'length' of undefined

**Comment by gamalielhere** [comment] 2018-03-16 20:31
@ATouhou is the issue still happening?

**Comment by gamalielhere** [comment] 2018-03-28 21:12
I'll close this for now. Feel free to open if the issue is still persists.

**Closed as completed by gamalielhere** 2018-03-28 21:12 UTC
