### ISSUE TITLE
click transaction hash link in success message doesn't work

### ISSUE THREAD

**Issue by dgobaud** [kvhnuke/etherwallet#1570] opened 2018-01-25 22:50 UTC
after submitting a transaction clicking the hash in the green success message at the bottom doesn't work in Chrome 63.0.3239.132 (Official Build) (64-bit)

**Comment by tayvano** [comment] 2018-02-01 16:41
Which page were you sending from?

**Comment by dgobaud** [comment] 2018-02-01 16:42
send offline

**Comment by gamalielhere** [comment] 2018-03-28 17:48
@dgobaud is this still an issue?

**Comment by dgobaud** [comment] 2018-03-28 18:10
not sure havent used this in a while

**Comment by gamalielhere** [comment] 2018-03-28 18:12
I see. I'll close this for now and will reopen when the issue is still persistent.

**Closed as completed by gamalielhere** 2018-03-28 18:12 UTC
