### ISSUE TITLE
Add Show On Trezor

### ISSUE THREAD

**Issue by zachoooo** [kvhnuke/etherwallet#651] opened 2017-06-26 18:08 UTC
The Trezor has a feature for bitcoin where it will display your receiving address so you can verify that no phishing or tampering has occurred with your address. Could you add this on MEW so that we can ensure our receiving addresses are secure?

**Comment by tayvano** [comment] 2017-06-26 18:33
I'm not familiar with this. Any documentation you can post here would be helpful.

**Comment by zachoooo** [comment] 2017-06-26 18:38
@tayvano The documentation for this feature is here: https://doc.satoshilabs.com/trezor-user/receivingpayments.html

I think it would go a long way to ensuring peace of mind for Trezor users.

**Comment by karelbilek** [comment] 2017-07-01 16:30
Hey

We first need to implement this in trezor-connect. We are working on it right now!

**Comment by tayvano** [comment] 2017-07-01 16:33
@runn1ng let me know what we can do it help. Be aware, tokens are a bit funky as the way you send them you send a 0 eth transaction to the token address with the receiving address and amount of tokens in the data field. Im on mobile but I can link the code if you want to see how we parse it for the confirmation modal

**Comment by karelbilek** [comment] 2017-08-08 14:21
Finally had time. (Bcash took a lot of time :( )

https://github.com/kvhnuke/etherwallet/issues/651

**Comment by karelbilek** [comment] 2017-08-08 14:25
~~~Hm, it seems to show slightly different addresses. Will look at what is going on~~~

Nevermind, it is working as intended

**Comment by karelbilek** [comment] 2017-08-10 09:46
Merged, this can be closed now

**Closed as completed** 2018-07-23 21:14 UTC
Labels: 2_hw wallets, 0_feature: low
