### ISSUE TITLE
No "Refund" menu

### ISSUE THREAD

**Issue by syndrael** [kvhnuke/etherwallet#1527] opened 2018-01-14 20:57 UTC
Hello,
i don't know if it's the right site to describe the issue.
On https://www.myetherwallet.com/#contracts, after typing Contract Address & ABI / JSON Interface and pressing Access, there is nothing in the "Choose function" menu.
On Gnome/Debian Firefox and Chromium, nothing.
May you help me ?
Regards.

**Comment by gamalielhere** [comment] 2018-03-14 18:03
@syndrael can you provide the token address and abi you used?

**Comment by gamalielhere** [comment] 2018-03-28 21:12
I'll close this for now. Feel free to open if the issue is still there.

**Closed as completed by gamalielhere** 2018-03-28 21:12 UTC
