### ISSUE TITLE
Deploy show wrong contract address

### ISSUE THREAD

**Issue by 3esmit** [kvhnuke/etherwallet#590] opened 2017-06-18 00:47 UTC
![image](https://user-images.githubusercontent.com/224810/27257266-343c6de4-53a6-11e7-8e48-ec658e5f1dfb.png)
https://rinkeby.etherscan.io/tx/0x5eefb5890c0b83ebe93700ec2ecf2d83f04e1dba60220a89310c37b81ea1401d
Probably related to a missing '0x'. https://github.com/ethereumjs/ethereumjs-util/issues/5

**Comment by tayvano** [comment] 2017-06-18 01:04
Dupe of #552

its on the todo list for today.

**Closed as completed by tayvano** 2017-06-18 01:04 UTC
Labels: x_duplicate
