### ISSUE TITLE
Nonce is detected incorrectly when account has pending transactions

### ISSUE THREAD

**Issue by Darayavaush** [kvhnuke/etherwallet#1590] opened 2018-02-01 23:07 UTC
I have 10 completed transactions and 2 pending ones (all sent via Metamask). When trying to send a new one (function call) via MEW, it creates a new one with nonce 11 instead of 13 and crashes with Error: replacement transaction underpriced.

**Comment by Simon0x** [comment] 2018-02-08 15:35
But this behavior is correct.
The network must first confirm the transactions before nonce is updated for your address.

**Comment by Darayavaush** [comment] 2018-02-08 18:23
But can't it check the pending transactions and at least offer the user a choice?

**Comment by adamdossa** [comment] 2018-02-09 13:48
You can use offline sending / signing to explicitly specify a nonce if needed.

**Comment by Darayavaush** [comment] 2018-02-09 15:33
It doesn't solve the problem of users unknowingly replacing a transaction. Also, IMO that's an unnecessary complication for a simple procedure.

**Comment by gamalielhere** [comment] 2018-07-23 20:43
Working as intended like @CryptoSmileee said. Closing issue. Don't hesitate to reopen.

**Closed as completed by gamalielhere** 2018-07-23 20:43 UTC

**Comment by Darayavaush** [comment] 2018-07-24 10:24
I honestly don't see how this is working is intended. It's trivial to silently overwrite a tx, potentially losing Ethereum if that tx was creating a contract (as I did, yay). Even a simple confirmation dialog "This will overwrite a tx. Are you sure you want to continue?" would be better than nothing.

**Comment by Simon0x** [comment] 2018-07-24 11:41
Why is it a problem to wait until the transactions are confirmed?
Since this is a very special behavior where you first send two transactions via MetaMask and then via MEW. Here you may have to wait. Otherwise send the transactions directly with MEW, then it's no problem?

**Comment by Darayavaush** [comment] 2018-07-24 14:15
But I just answered that. It is a problem because it's trivial to silently overwrite a tx, potentially losing Ethereum if that tx was creating a contract. How can you not see how this behavior is very much undesirable, to say the least?
Also, one pending transaction is enough, and it doesn't necessarily have to come from Metamask, just from any other source outside MEW.
