### ISSUE TITLE
Node does not exist, contact support@myetherwallet.com CODE:localstorageNodeMissing while trying to add custom token aeternity

### ISSUE THREAD

**Issue by onpars** [kvhnuke/etherwallet#1240] opened 2017-11-09 15:23 UTC
Using mew locally. Just now cloned fresh from git.

file:///home/user/etherwallet/dist/index.html#view-wallet-info

Used a public key (view only).

Add custom token.

    0x5ca9a71b1d01849c0a95490cc00559717fcf0d1d

    AE

    18

Save.

Got an error.

> Node does not exist, contact support@myetherwallet.com CODE:localstorageNodeMissing

**Comment by tayvano** [comment] 2017-11-11 10:34
What browser are you using? 

If in Chrome, try to clear local storage and see if that resolves. If not Chrome, google "clear local storage from site [browser name]"

**Comment by tayvano** [comment] 2017-11-13 12:03
Did this solve it?

**Comment by onpars** [comment] 2017-11-22 15:23
Using both Chrome and Firefox on Linux.

Was starting with fresh user profile folders.

Didn't solve it.

**Comment by onpars** [comment] 2017-11-22 15:24
Perhaps because it was offline? Tried using MEW offline.

**Comment by xsmile** [comment] 2018-03-13 16:32
Indeed, the issue is still present and it happens when using MEW locally/offline.

Is there any way to interact with custom tokens without using MEW online?

**Comment by gamalielhere** [comment] 2018-03-13 21:16
@xsmile can you send me the token, symbol and decimal? I'll try testing it on my end. It seems to work for the tokens I tried.

**Comment by xsmile** [comment] 2018-03-13 21:30
@gamalielhere This seems to be browser-specific. I tested it again with Firefox 59.0 and adding a custom token worked. It fails with Chromium 65.0.3325.146 however and the aforementioned error message is printed inside a red popup in the footer.

The custom token address doesn't seem to matter, I used [0x123ab195dd38b1b40510d467a6a359b201af056f](https://etherscan.io/token/0x123ab195dd38b1b40510d467a6a359b201af056f) with 8 decimals as LGO.

**Comment by gamalielhere** [comment] 2018-03-13 21:39
@xsmile Seems to be working on Chrome Version 65.0.3325.162. I'll try and spin up a Chromium instance and check there too.

**Comment by xsmile** [comment] 2018-03-13 21:50
@gamalielhere ~~Ok, I did a few more tests and found out that Chromium works fine but the patched Chromium version I used earlier that removes some telemetry features does not.~~

Sorry for the trouble.

EDIT:
Blocked third-party cookies in Chromium are the issue, see https://github.com/kvhnuke/etherwallet/pull/739.
You might want to mention it in the wiki.

**Comment by gamalielhere** [comment] 2018-03-13 23:18
@xsmile Unfortunately no. I did find this reddit post: https://www.reddit.com/r/BATProject/comments/75ry44/difficulty_transferring_bat_from_myetherwallet_to/

I'll close this for now and reopen it if the issue does persist.

**Comment by xsmile** [comment] 2018-03-13 23:24
@gamalielhere Please see my updated message above. Disabled third-party cookies in Chromium are causing the issue.

While Firefox allows local cookies to be set, Chrome does not. The solution is to add `file:///*` to the cookie exception list, if third-party cookies are blocked.

**Comment by gamalielhere** [comment] 2018-03-13 23:45
@xsmile Thanks for finding it! I'll update it tomorrow and tag your github user if you don't mind. I'll go ahead and close this issue.

**Closed as completed by gamalielhere** 2018-03-13 23:45 UTC
Labels: 0_support, 2_node
